import type { Metadata } from 'next';
import RootLayoutPage from '@Component/admin/container/rootLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <RootLayoutPage>{children}</RootLayoutPage>;
}
